---
title: "nn2poly-04-testing_the_implementation_with_generated_data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{nn2poly-04-testing_the_implementation_with_generated_data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(nn2poly)
library(keras)
library(tensorflow)
```

This vignette contains several usecases of the `nn2poly` package applied to some precomputed examples that allow us to test special situations and control the behavior of the NN2Poly algorithm.

## Example 0

```{r}

  nn2poly_example <- nn2poly_example0  

  # Get the needed data
  weights_list <- nn2poly_example$weights_list
  af_string_list <- nn2poly_example$af_string_list
  af_derivatives_list <- nn2poly_example$af_derivatives_list
  q_taylor_vector <- nn2poly_example$q_taylor_vector

  result <- nn2poly_algorithm(
    weights_list = weights_list,
    af_string_list = af_string_list,
    q_taylor_vector = q_taylor_vector,
    historical_coeffs = TRUE
  )

  # Comparamos el potencial en la segunda capa para neurona 1
  # Note that in new, 2 denotes neuron 1 as 1  are the labels
  print("Potential u at layer 2, neuron 1")
  print(result[[3]][[2]])

  print("Output y at layer 2, neuron 1")
  print(result[[4]][[1]][4])
  print(result[[4]][[2]][4])

  print(1/2*result[[3]][[2]][4]+1/8*result[[3]][[2]][2]^2+
          1/4*result[[3]][[2]][1]*result[[3]][[2]][4])

  0.633518334
  


```



## Example 1

```{r}

  nn2poly_example <- nn2poly_example1

  # Get the needed data
  weights_list <- nn2poly_example$weights_list
  af_string_list <- nn2poly_example$af_string_list
  af_derivatives_list <- nn2poly_example$af_derivatives_list
  q_taylor_vector <- nn2poly_example$q_taylor_vector
  test_y <- nn2poly_example$test_y
  test_x <- nn2poly_example$test_x

  result <- nn2poly_algorithm(
    weights_list = weights_list,
    af_string_list = af_string_list,
    q_taylor_vector = q_taylor_vector,
    historical_coeffs = TRUE
  )

  labels <- result[[length(historical_coeffs)]][[1]]
  coeffs <- result[[length(historical_coeffs)]][[2]]
  
  # Obtain the predicted values for the test data with our Polynomial Regression
  n_test <- length(test_y)
  prediction_PR <- rep(0, n_test)
  
  for (i in 1:n_test) {
    prediction_PR[i] <- eval_poly(test_x, labels = labels, coeffs = coeffs)
  }
  
  # FALTA AÑADIR LA NN A LOS DATA PARA PODER USAR PREDICT
  
  # Obtain the predicted values with the NN to compare them
  prediction_NN <- predict(nn, test_x)

  plot_NN_PR_comparison(prediction_PR, prediction_NN)
```


