// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "nn2poly_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// obtain_taylor_vector
Term obtain_taylor_vector(const Term& taylor_orders, const Functions& af_string_list);
RcppExport SEXP _nn2poly_obtain_taylor_vector(SEXP taylor_ordersSEXP, SEXP af_string_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Term& >::type taylor_orders(taylor_ordersSEXP);
    Rcpp::traits::input_parameter< const Functions& >::type af_string_list(af_string_listSEXP);
    rcpp_result_gen = Rcpp::wrap(obtain_taylor_vector(taylor_orders, af_string_list));
    return rcpp_result_gen;
END_RCPP
}
// obtain_derivatives_list
CoeffsList obtain_derivatives_list(const Term& taylor_orders, const Functions& af_string_list, double a);
RcppExport SEXP _nn2poly_obtain_derivatives_list(SEXP taylor_ordersSEXP, SEXP af_string_listSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Term& >::type taylor_orders(taylor_ordersSEXP);
    Rcpp::traits::input_parameter< const Functions& >::type af_string_list(af_string_listSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(obtain_derivatives_list(taylor_orders, af_string_list, a));
    return rcpp_result_gen;
END_RCPP
}
// alg_non_linear
Weights alg_non_linear(const Weights& coeffs_input, const Terms& labels_input, const Terms& labels_output, const int previous_order, const int q_layer, const Coeffs& g);
RcppExport SEXP _nn2poly_alg_non_linear(SEXP coeffs_inputSEXP, SEXP labels_inputSEXP, SEXP labels_outputSEXP, SEXP previous_orderSEXP, SEXP q_layerSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Weights& >::type coeffs_input(coeffs_inputSEXP);
    Rcpp::traits::input_parameter< const Terms& >::type labels_input(labels_inputSEXP);
    Rcpp::traits::input_parameter< const Terms& >::type labels_output(labels_outputSEXP);
    Rcpp::traits::input_parameter< const int >::type previous_order(previous_orderSEXP);
    Rcpp::traits::input_parameter< const int >::type q_layer(q_layerSEXP);
    Rcpp::traits::input_parameter< const Coeffs& >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(alg_non_linear(coeffs_input, labels_input, labels_output, previous_order, q_layer, g));
    return rcpp_result_gen;
END_RCPP
}
// nn2poly_algorithm
List nn2poly_algorithm(const Layers& layers, const Functions& af_list, int max_order, bool keep_layers, const Term& taylor_orders, double a);
RcppExport SEXP _nn2poly_nn2poly_algorithm(SEXP layersSEXP, SEXP af_listSEXP, SEXP max_orderSEXP, SEXP keep_layersSEXP, SEXP taylor_ordersSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Layers& >::type layers(layersSEXP);
    Rcpp::traits::input_parameter< const Functions& >::type af_list(af_listSEXP);
    Rcpp::traits::input_parameter< int >::type max_order(max_orderSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_layers(keep_layersSEXP);
    Rcpp::traits::input_parameter< const Term& >::type taylor_orders(taylor_ordersSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(nn2poly_algorithm(layers, af_list, max_order, keep_layers, taylor_orders, a));
    return rcpp_result_gen;
END_RCPP
}
// combinations_with_repetition
Terms combinations_with_repetition(int n, int k);
RcppExport SEXP _nn2poly_combinations_with_repetition(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(combinations_with_repetition(n, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nn2poly_obtain_taylor_vector", (DL_FUNC) &_nn2poly_obtain_taylor_vector, 2},
    {"_nn2poly_obtain_derivatives_list", (DL_FUNC) &_nn2poly_obtain_derivatives_list, 3},
    {"_nn2poly_alg_non_linear", (DL_FUNC) &_nn2poly_alg_non_linear, 6},
    {"_nn2poly_nn2poly_algorithm", (DL_FUNC) &_nn2poly_nn2poly_algorithm, 6},
    {"_nn2poly_combinations_with_repetition", (DL_FUNC) &_nn2poly_combinations_with_repetition, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_nn2poly(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
