# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

obtain_final_poly_order <- function(max_order, taylor_orders) {
    .Call(`_nn2poly_obtain_final_poly_order`, max_order, taylor_orders)
}

obtain_taylor_vector <- function(taylor_orders, af_string_list) {
    .Call(`_nn2poly_obtain_taylor_vector`, taylor_orders, af_string_list)
}

obtain_derivatives_list <- function(taylor_orders, af_string_list) {
    .Call(`_nn2poly_obtain_derivatives_list`, taylor_orders, af_string_list)
}

obtain_partitions_with_labels <- function(p, q_max) {
    .Call(`_nn2poly_obtain_partitions_with_labels`, p, q_max)
}

alg_non_linear <- function(coeffs_input, labels_input, labels_output, taylor_orders, current_layer, g, partitions_labels, partitions) {
    .Call(`_nn2poly_alg_non_linear`, coeffs_input, labels_input, labels_output, taylor_orders, current_layer, g, partitions_labels, partitions)
}

nn2poly_algorithm <- function(layers, af_list, max_order, keep_layers, taylor_orders) {
    .Call(`_nn2poly_nn2poly_algorithm`, layers, af_list, max_order, keep_layers, taylor_orders)
}

combinations_with_repetition <- function(n, k) {
    .Call(`_nn2poly_combinations_with_repetition`, n, k)
}

generate_partitions <- function(p, q_max) {
    .Call(`_nn2poly_generate_partitions`, p, q_max)
}

