# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alg_linear <- function(weights_layer, coeffs_list_input) {
    .Call(`_nn2poly_alg_linear`, weights_layer, coeffs_list_input)
}

combinations_with_repetition <- function(n, k) {
    .Call(`_nn2poly_combinations_with_repetition`, n, k)
}

generate_partitions <- function(p, q_max) {
    .Call(`_nn2poly_generate_partitions`, p, q_max)
}

select_allowed_partitions_loop <- function(all_partitions_for_this_label, q_previous_layer) {
    .Call(`_nn2poly_select_allowed_partitions_loop`, all_partitions_for_this_label, q_previous_layer)
}

